---
extends:
  - eslint:recommended
  - plugin:import/errors

parser: babel-eslint

parserOptions:
  sourceType: module
  ecmaVersion: 6

env:
  browser: true
  node: true
  es6: true

globals:
  PRODUCTION: false
  DEBUG: false
  WHOAMI: false

rules:
  no-unused-vars: 1
  react/jsx-uses-vars: 2
  no-debugger: 2
  no-console: 0

settings:
  import/resolver: 'webpack'
  import/ignore: ['node_modules']

plugins:
  - react
  - import
